# Generated by Django 5.2.6 on 2025-12-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_id', models.CharField(max_length=100, unique=True)),
                ('title', models.TextField()),
                ('disease', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('sponsor', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
