# Generated by Django 5.2.6 on 2025-12-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicaltrial',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='clinicaltrial',
            name='location',
        ),
        migrations.RemoveField(
            model_name='clinicaltrial',
            name='sponsor',
        ),
        migrations.RemoveField(
            model_name='clinicaltrial',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='clinicaltrial',
            name='status',
        ),
        migrations.AddField(
            model_name='clinicaltrial',
            name='health_condition',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clinicaltrial',
            name='intervention_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clinicaltrial',
            name='locations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clinicaltrial',
            name='recruitment_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clinicaltrial',
            name='type_of_trial',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
